tyche {
  bot-token = ${?TYCHE_TLGRM_BOT_TOKEN}
  items-file = "items.json"
  items-file = ${?TYCHE_ITEMS_FILE}
  ttl {
    random = 1m
    random = ${?TYCHE_RANDOM_TTL}

    set-items   = 5m
    set-items   = ${?TYCHE_SET_ITEMS_TTL}
  }
}
